/*

 * Cryptographic API.

 *

 * AES Cipher Algorithm.

 *

 * Based on Brian Gladman's code.

 *

 * Linux developers:

 *  Alejandro Sobarzo <alemetal.1993@gmail.com>

 *  Gaston Velasquez <gaston.velasquezjr99@gmail.com>

 *  Tomas Castillo <tomas_castillo2.0@hotmail.com>

 *

 * This program is free software; you can redistribute it and/or modify

 * it under the terms of the GNU General Public License as published by

 * the Free Software Foundation; either version 2 of the License, or

 * (at your option) any later version.

 */
package principal;


import gestionbd.Gestionbd;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    
public Gestionbd gbd=new Gestionbd();

    public Principal() {
     
        initComponents();
       this.setLocationRelativeTo(null);
this.setTitle("Biblioteca Shoe");
this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/150360.png")).getImage());
        noEditable();
        configurarBTNCliente();
    }
public void configurarBTNCliente(){
ButtonGroup b=new ButtonGroup();
b.add(boton1);
b.add(btnIDPRESTAMO);
b.add(btnRUT);
btnRUT.setSelected(true);
}

public void noEditable(){
      txtLibro.setEnabled(false);
      txtLibronombre.setEnabled(false);
     txtLibroautor.setEnabled(false);
    txtLibrotipo.setEnabled(false);
      txtPrestamo.setEnabled(false);
      txtPlibro.setEnabled(false);
    txtPprestamo.setEnabled(false);
     txtPdevolucion.setEnabled(false);
    txtPrut.setEnabled(false);
     txtNombre.setEnabled(false);
     txtApellido.setEnabled(false);
     txtEdad.setEnabled(false);
     txtDire.setEnabled(false);
     txtStock.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tmostrar2 = new javax.swing.JTable();
        btnmostrar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmostrar = new javax.swing.JTable();
        btnmostrar = new javax.swing.JButton();
        btnmostrar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tmostrar1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        txtDire = new javax.swing.JTextField();
        btnRUT = new javax.swing.JRadioButton();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        txtEdad = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jCheckBox11 = new javax.swing.JCheckBox();
        txtApellido = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        txtLibrotipo = new javax.swing.JTextField();
        txtLibroagregar = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtLibro = new javax.swing.JTextField();
        txtLibronombre = new javax.swing.JTextField();
        txtLibroautor = new javax.swing.JTextField();
        boton1 = new javax.swing.JRadioButton();
        btnSTOCK = new javax.swing.JCheckBox();
        txtStock = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtPlibro = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        txtPdevolucion = new javax.swing.JTextField();
        jCheckBox6 = new javax.swing.JCheckBox();
        btnAgregarprestamo = new javax.swing.JButton();
        txtPprestamo = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        txtPrut = new javax.swing.JTextField();
        txtPrestamo = new javax.swing.JTextField();
        btnIDPRESTAMO = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtELIMINARPRESTAMO = new javax.swing.JTextField();
        btnELIMINARPRESTAMO = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txtELIMINARLIBRO = new javax.swing.JTextField();
        btnELIMINARLIBRO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtidlibro = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtADLN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtADLA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtADLT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtStockk = new javax.swing.JTextField();
        btnSTOCKK = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        txtADLN1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtADLA1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtADLT1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnActualizaridprestamo = new javax.swing.JButton();
        btnActualizarfechap = new javax.swing.JButton();
        txtidlibro1 = new javax.swing.JTextField();
        btnActualizarfechad = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtADLT2 = new javax.swing.JTextField();
        btnActualizarrutcli = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        txtADLT3 = new javax.swing.JTextField();
        txtADLA2 = new javax.swing.JTextField();
        btnActualizarrutcli1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtADLT4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnActualizaridprestamo1 = new javax.swing.JButton();
        btnActualizarfechap1 = new javax.swing.JButton();
        txtidlibro2 = new javax.swing.JTextField();
        btnActualizarfechad1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtADLN2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnIntegrantes = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CONSULTADOS = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        CONSULTATRES = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tmostrar2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID PRESTAMO", "ID LIBRO", "FECHA PRESTAMO", "FECHA_DEVOLUCION", "RUT_CLIENTE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tmostrar2);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 980, 165));

        btnmostrar2.setText("VER PRESTAMOS");
        btnmostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrar2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnmostrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 960, -1));

        tmostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "EDAD", "DIRECCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tmostrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tmostrarKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tmostrar);
        if (tmostrar.getColumnModel().getColumnCount() > 0) {
            tmostrar.getColumnModel().getColumn(4).setHeaderValue("DIRECCION");
        }

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 975, 149));

        btnmostrar.setText("VER USUARIOS");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        jPanel6.add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 975, -1));

        btnmostrar1.setText("VER LIBROS");
        btnmostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnmostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 975, -1));

        tmostrar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "AUTOR", "TIPO DE LIBRO", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tmostrar1);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 975, 173));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca-arus-1-1.jpg"))); // NOI18N
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 670));

        jTabbedPane1.addTab("Mostrar (Consulta 1 tabla) ", jPanel6);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("CLIENTE"));
        jPanel14.setOpaque(false);

        btnRUT.setText("RUT");
        btnRUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUTActionPerformed(evt);
            }
        });

        jCheckBox8.setText("NOMBRE");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("APELLIDO");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("EDAD");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jCheckBox11.setText("DIRECCION");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jCheckBox11)
                        .addGap(18, 18, 18)
                        .addComponent(txtDire, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jCheckBox10)
                        .addGap(52, 52, 52)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(btnRUT))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jCheckBox9)
                        .addGap(28, 28, 28)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRUT)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox10)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(txtDire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 290));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("LIBRO"));
        jPanel15.setOpaque(false);

        txtLibroagregar.setText("AGREGAR");
        txtLibroagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroagregarActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Nombre");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Autor");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Tipo");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        txtLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroActionPerformed(evt);
            }
        });

        txtLibronombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibronombreActionPerformed(evt);
            }
        });

        boton1.setText("ID LIBRO");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        btnSTOCK.setText("Stock");
        btnSTOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSTOCKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(txtLibroagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(btnSTOCK))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLibroautor)
                    .addComponent(txtLibrotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(txtLibronombre)
                    .addComponent(txtLibro)
                    .addComponent(txtStock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(txtLibronombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(txtLibroautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(txtLibrotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSTOCK)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtLibroagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 420, 280));

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("PRESTAMO"));
        jPanel16.setOpaque(false);

        jCheckBox1.setText("ID LIBRO");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        txtPlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlibroActionPerformed(evt);
            }
        });

        jCheckBox5.setText("FECHA PRESTAMO");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("FECHA DEVOLUCION");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        btnAgregarprestamo.setText("AGREGAR");
        btnAgregarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarprestamoActionPerformed(evt);
            }
        });

        jCheckBox7.setText("RUT CLIENTE");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        txtPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrestamoActionPerformed(evt);
            }
        });

        btnIDPRESTAMO.setText("ID PRESTAMO");
        btnIDPRESTAMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDPRESTAMOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addGap(28, 28, 28)
                        .addComponent(txtPprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIDPRESTAMO)
                            .addComponent(jCheckBox1))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrut, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPdevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIDPRESTAMO)
                    .addComponent(txtPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(txtPlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(txtPprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(txtPdevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(txtPrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarprestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 290));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro-en-blanco.jpg"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1010, 670));

        jTabbedPane1.addTab("Agregar ", jPanel1);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("PRESTAMO"));
        jPanel17.setOpaque(false);

        jLabel2.setText("INGRESE ID DE PRESTAMO A ELIMINAR");

        btnELIMINARPRESTAMO.setText("ELIMINAR");
        btnELIMINARPRESTAMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELIMINARPRESTAMOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtELIMINARPRESTAMO)
                    .addComponent(btnELIMINARPRESTAMO, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtELIMINARPRESTAMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnELIMINARPRESTAMO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("CLIENTE"));
        jPanel18.setOpaque(false);

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel15.setText("INGRESE RUT DE CLIENTE PARA ELIMINAR ");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("LIBRO"));
        jPanel19.setOpaque(false);

        btnELIMINARLIBRO.setText("ELIMINAR");
        btnELIMINARLIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELIMINARLIBROActionPerformed(evt);
            }
        });
        btnELIMINARLIBRO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnELIMINARLIBROKeyTyped(evt);
            }
        });

        jLabel1.setText("INGRESE ID DE LIBRO A ELIMINAR");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtELIMINARLIBRO)
                    .addComponent(btnELIMINARLIBRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtELIMINARLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnELIMINARLIBRO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 240, 150));

        jLabel24.setText("PARA MOSTRAR LOS CLIENTES, PRESTAMOS, LIBROS ELIMINADOS PORFAVOR REINICIAR EL SISTEMA");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 600, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro-en-blanco.jpg"))); // NOI18N
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1010, 670));

        jTabbedPane1.addTab("Eliminar ", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("LIBROS"));
        jPanel11.setOpaque(false);

        jButton2.setText("ACTUALIZAR ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ACTUALIZAR ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("NOMBRE");

        jLabel7.setText("AUTOR");

        jLabel8.setText("LIBRO");

        jLabel3.setText("ID LIBRO");

        jButton1.setText("ACTUALIZAR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel23.setText("STOCK");

        btnSTOCKK.setText("ACTUALIZAR");
        btnSTOCKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSTOCKKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtidlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel23))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtADLT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtStockk))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSTOCKK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtADLA)
                            .addComponent(txtADLN, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 397, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtADLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtidlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtADLA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtADLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtStockk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSTOCKK))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 960, 200));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("PRESTAMO"));
        jPanel12.setOpaque(false);

        jLabel9.setText("FECHA PRESTAMO");

        jLabel10.setText("FECHA DEVOLUCION");

        jLabel4.setText("ID PRESTAMO");

        btnActualizaridprestamo.setText("ACTUALIZAR ");
        btnActualizaridprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaridprestamoActionPerformed(evt);
            }
        });

        btnActualizarfechap.setText("ACTUALIZAR ");
        btnActualizarfechap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarfechapActionPerformed(evt);
            }
        });

        btnActualizarfechad.setText("ACTUALIZAR ");
        btnActualizarfechad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarfechadActionPerformed(evt);
            }
        });

        jLabel11.setText("ID LIBRO");

        jLabel12.setText("RUT CLIENTE");

        btnActualizarrutcli.setText("ACTUALIZAR ");
        btnActualizarrutcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarrutcliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtidlibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(59, 59, 59)
                        .addComponent(txtADLT2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtADLA1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtADLN1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtADLT1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarfechap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizaridprestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarfechad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarrutcli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizaridprestamo)
                    .addComponent(txtADLN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtidlibro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarfechap)
                    .addComponent(txtADLA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarfechad)
                    .addComponent(txtADLT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtADLT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarrutcli)))
        );

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 961, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("CLIENTE"));
        jPanel13.setOpaque(false);

        btnActualizarrutcli1.setText("ACTUALIZAR ");
        btnActualizarrutcli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarrutcli1ActionPerformed(evt);
            }
        });

        jLabel13.setText("EDAD");

        jLabel5.setText("RUT CLIENTE");

        btnActualizaridprestamo1.setText("ACTUALIZAR ");
        btnActualizaridprestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaridprestamo1ActionPerformed(evt);
            }
        });

        btnActualizarfechap1.setText("ACTUALIZAR ");
        btnActualizarfechap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarfechap1ActionPerformed(evt);
            }
        });

        btnActualizarfechad1.setText("ACTUALIZAR ");
        btnActualizarfechad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarfechad1ActionPerformed(evt);
            }
        });

        jLabel14.setText("NOMBRE");

        txtADLN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADLN2ActionPerformed(evt);
            }
        });

        jLabel16.setText("DIRECCION");

        jLabel17.setText("APELLIDO");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtidlibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtADLT4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtADLT3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtADLA2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtADLN2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarfechap1)
                    .addComponent(btnActualizaridprestamo1)
                    .addComponent(btnActualizarfechad1)
                    .addComponent(btnActualizarrutcli1))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizaridprestamo1)
                    .addComponent(txtADLN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtidlibro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarfechap1)
                    .addComponent(txtADLA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarfechad1)
                    .addComponent(txtADLT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtADLT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarrutcli1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 961, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro-en-blanco.jpg"))); // NOI18N
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1010, 670));

        jTabbedPane1.addTab("Actualizar Datos ", jPanel10);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIntegrantes.setText("Quienes somos");
        btnIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrantesActionPerformed(evt);
            }
        });
        jPanel2.add(btnIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 230, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblioteca-arus-1-1.jpg"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 670));

        jTabbedPane1.addTab("Quienes somos", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CONSULTADOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "LIBRO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(CONSULTADOS);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 961, 191));

        jButton4.setText("VER CONSULTA A DOS TABLAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 222, 961, -1));

        CONSULTATRES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "NOMBRE", "APELLIDO", "LIBRO", "FECHA PRESTAMO", "FECHA DEVOLUCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(CONSULTATRES);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 265, 961, 193));

        jButton5.setText("VER CONSULTA A TRES TABLAS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 476, 961, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro-en-blanco.jpg"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1010, 670));

        jTabbedPane1.addTab("Consultas 2 & 3 Tablas", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtADLN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADLN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtADLN2ActionPerformed

    private void btnActualizarfechad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarfechad1ActionPerformed
        String a=txtidlibro2.getText();
        int b=Integer.parseInt(txtADLT4.getText());
        gbd.actualizardatosEDADcliente(a, b);
    }//GEN-LAST:event_btnActualizarfechad1ActionPerformed

    private void btnActualizarfechap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarfechap1ActionPerformed
        String a=txtidlibro2.getText();
        String b=txtADLA2.getText();
        gbd.actualizardatosAPELLIDOcliente(a, b);
    }//GEN-LAST:event_btnActualizarfechap1ActionPerformed

    private void btnActualizaridprestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaridprestamo1ActionPerformed
        String a=txtidlibro2.getText();
        String b=txtADLN2.getText();
        gbd.actualizardatosNOMBREcliente(a,b);
    }//GEN-LAST:event_btnActualizaridprestamo1ActionPerformed

    private void btnActualizarrutcli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarrutcli1ActionPerformed

        String a=txtidlibro2.getText();
        String b=txtADLT3.getText();
        gbd.actualizardatosDIRECCIONcliente(a, b);
    }//GEN-LAST:event_btnActualizarrutcli1ActionPerformed

    private void btnActualizarrutcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarrutcliActionPerformed
        int a=Integer.parseInt(txtidlibro1.getText());
        String b=txtADLT2.getText();
        gbd.actualizarprestamorut(a,b);
    }//GEN-LAST:event_btnActualizarrutcliActionPerformed

    private void btnActualizarfechadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarfechadActionPerformed
        int a=Integer.parseInt(txtidlibro1.getText());
        String b=txtADLT1.getText();
        gbd.actualizarprestamofechad(a, b);
    }//GEN-LAST:event_btnActualizarfechadActionPerformed

    private void btnActualizarfechapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarfechapActionPerformed
        int a=Integer.parseInt(txtidlibro1.getText());
        String b=txtADLA1.getText();
        gbd.actualizarprestamofechap(a, b);
    }//GEN-LAST:event_btnActualizarfechapActionPerformed

    private void btnActualizaridprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaridprestamoActionPerformed
        int a=Integer.parseInt(txtidlibro1.getText());
        int b=Integer.parseInt(txtADLN1.getText());
        gbd.actualizarprestamoidlibro(a,b);
    }//GEN-LAST:event_btnActualizaridprestamoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String n=txtADLN.getText();
        int t=Integer.parseInt(txtidlibro.getText());
        gbd.actualizardatosNOMBRElibro(t,n);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String n=txtADLT.getText();
        int t=Integer.parseInt(txtidlibro.getText());
        gbd.actualizardatostipo(t,n);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if(jCheckBox4.isSelected()){
            txtLibrotipo.setEnabled(true);
        } else{
            txtLibrotipo.setEnabled(false);
            txtLibrotipo.setText("");
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected()){
            txtLibroautor.setEnabled(true);
        } else{
            txtLibroautor.setEnabled(false);
            txtLibroautor.setText("");
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

        if(jCheckBox2.isSelected()){
            txtLibronombre.setEnabled(true);
        } else{
            txtLibronombre.setEnabled(false);
            txtLibronombre.setText("");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
            if(boton1.isSelected()){
           txtLibro.setEnabled(true);
        }else{
           txtLibro.setEnabled(false);
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void txtLibroagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroagregarActionPerformed
        try{
            int id=0;
            id = Integer.parseInt(txtLibro.getText());
            String nombre= txtLibronombre.getText();
            String autor = txtLibroautor.getText();
            String tipo = txtLibrotipo.getText();
            int stock=Integer.parseInt(txtStock.getText());
            if(nombre.equals("") || autor.equals("") || tipo.equals("") || id==0){
                JOptionPane.showMessageDialog(null, "Error, debes rellenar todos los datos","ERROR",JOptionPane.WARNING_MESSAGE);
            }
            else{
                gbd.insertarLibro(id, nombre, autor, tipo,stock);
            txtLibro.setText("");
            txtLibronombre.setText("");
                    txtLibroautor.setText("");
                            txtLibrotipo.setText("");
                            txtStock.setText("");
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Debes ingresar todos los campos","ERROR INSERCION",JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_txtLibroagregarActionPerformed

    private void txtLibronombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibronombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibronombreActionPerformed

    private void txtLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            if(txtCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un rut","ERROR",JOptionPane.WARNING_MESSAGE);
            }else{String rut=txtCliente.getText();
            gbd.eliminarCliente(rut);
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Debe ingresar un id","ERROR", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnELIMINARPRESTAMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELIMINARPRESTAMOActionPerformed
        try{ int id=Integer.parseInt(txtELIMINARPRESTAMO.getText());
            gbd.eliminarPrestamo(id);}catch(Exception e){JOptionPane.showMessageDialog(null,"Debe ingresar un id","ERROR", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_btnELIMINARPRESTAMOActionPerformed

    private void btnELIMINARLIBROKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnELIMINARLIBROKeyTyped

    }//GEN-LAST:event_btnELIMINARLIBROKeyTyped

    private void btnELIMINARLIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELIMINARLIBROActionPerformed
        try{
            int id=Integer.parseInt(txtELIMINARLIBRO.getText());
            gbd.eliminarlibro(id);
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Debe ingresar un id","ERROR", JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_btnELIMINARLIBROActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        if(jCheckBox11.isSelected()){
            txtDire.setEnabled(true);
        }else{
            txtDire.setEnabled(false);
            txtDire.setText("");
        }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        if(jCheckBox10.isSelected()){
            txtEdad.setEnabled(true);
        }else{
            txtEdad.setEnabled(false);
             txtEdad.setText("");
        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        if(jCheckBox9.isSelected()){
            txtApellido.setEnabled(true);
        }else{
            txtApellido.setEnabled(false);
            txtApellido.setText("");
        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        if(jCheckBox8.isSelected()){
            txtNombre.setEnabled(true);
        }else{
            txtNombre.setEnabled(false);
            txtNombre.setText("");
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            int edad=0;
            String rut = txtRut.getText();
            String nombre= txtNombre.getText();
            String apellido = txtApellido.getText();
            edad=Integer.parseInt(txtEdad.getText());
            String direccion = txtDire.getText();
            if(rut.equals("") || nombre.equals("") || apellido.equals("") || edad==0 || direccion.equals("")){
                JOptionPane.showMessageDialog(null, "Error, debes rellenar todos los datos","ERROR",JOptionPane.WARNING_MESSAGE);
            }
            else{
                gbd.insertarCliente(rut,nombre,apellido,edad,direccion);
            txtRut.setText("");
                    txtNombre.setText("");
                    txtApellido.setText("");
                            txtEdad.setText("");
                            txtDire.setText("");
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Debes ingresar todos los campos","ERROR ",JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        if(jCheckBox7.isSelected()){
            txtPrut.setEnabled(true);
        }else{
            txtPrut.setEnabled(false);
            txtPrut.setText("");
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        if(jCheckBox6.isSelected()){
            txtPdevolucion.setEnabled(true);
        }else{
            txtPdevolucion.setEnabled(false);
            txtPdevolucion.setText("");
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(jCheckBox5.isSelected()){
            txtPprestamo.setEnabled(true);
        }else{
            txtPprestamo.setEnabled(false);
            txtPprestamo.setText("");
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            txtPlibro.setEnabled(true);
        }else{
            txtPlibro.setEnabled(false);
            txtPlibro.setText("");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnAgregarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarprestamoActionPerformed
        try{
            int id=0;
            int idd=0;
            id = Integer.parseInt(txtPrestamo.getText());
            idd = Integer.parseInt(txtPlibro.getText());
            String pp=txtPprestamo.getText();
            String dd =txtPdevolucion.getText();
            String rutt=txtPrut.getText();
            if(id==0 || idd==0 || pp.equals("") || dd.equals("") || rutt.equals("")){
                JOptionPane.showMessageDialog(null, "Error, debes rellenar todos los datos","ERROR",JOptionPane.WARNING_MESSAGE);
            }
            else{
                
                gbd.insertarPrestamo(id, idd, pp,dd, rutt);
            txtPrestamo.setText("");
            txtPlibro.setText("");
            txtPprestamo.setText("");
            txtPdevolucion.setText("");
            txtPrut.setText("");
            
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Debes ingresar todos los campos","ERROR INSERCION",JOptionPane.WARNING_MESSAGE);}
    }//GEN-LAST:event_btnAgregarprestamoActionPerformed

    private void txtPlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlibroActionPerformed

    }//GEN-LAST:event_txtPlibroActionPerformed

    private void btnmostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrar1ActionPerformed
        gbd.mostrarLibros(tmostrar1);
         tmostrar1.setVisible(false);
        tmostrar1.setVisible(true);
    }//GEN-LAST:event_btnmostrar1ActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        gbd.mostrarClientes(tmostrar);
         tmostrar.setVisible(false);
        tmostrar.setVisible(true);
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void tmostrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmostrarKeyReleased

    }//GEN-LAST:event_tmostrarKeyReleased

    private void btnmostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrar2ActionPerformed
        gbd.mostrarPrestamo(tmostrar2);
        tmostrar2.setVisible(false);
        tmostrar2.getModel();
        tmostrar2.setVisible(true);
    }//GEN-LAST:event_btnmostrar2ActionPerformed

    private void txtPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrestamoActionPerformed

    private void btnRUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUTActionPerformed
           
    }//GEN-LAST:event_btnRUTActionPerformed

    private void btnIDPRESTAMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDPRESTAMOActionPerformed
                  if(btnIDPRESTAMO.isSelected()){
            txtPrestamo.setEnabled(true);
        }else{
            txtPrestamo.setEnabled(false);
        }
    }//GEN-LAST:event_btnIDPRESTAMOActionPerformed

    private void btnIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrantesActionPerformed
        Integrantes i=new Integrantes();
       i.setLocationRelativeTo(null);
      i.setVisible(true);
      this.setVisible(false);
      
    }//GEN-LAST:event_btnIntegrantesActionPerformed

    private void btnSTOCKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSTOCKKActionPerformed
      int id=Integer.parseInt(txtidlibro.getText());
        int stock=Integer.parseInt(txtStockk.getText());
        gbd.actualizardatosSTOCK(id, stock);
    }//GEN-LAST:event_btnSTOCKKActionPerformed

    private void btnSTOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSTOCKActionPerformed
       if(btnSTOCK.isSelected()){
            txtStock.setEnabled(true);
        }else{
            txtStock.setEnabled(false);
            txtStock.setText("");
        }
        
        
        
    }//GEN-LAST:event_btnSTOCKActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        gbd.CONSULTAdostablas(CONSULTADOS);
        CONSULTADOS.setVisible(false);
        CONSULTADOS.getModel();
        CONSULTADOS.setVisible(true);
      
      
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         gbd.CONSULTATREStablas(CONSULTATRES);
        CONSULTATRES.setVisible(false);
        CONSULTATRES.getModel();
        CONSULTATRES.setVisible(true);
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String n=txtADLA.getText();
        int t=Integer.parseInt(txtidlibro.getText());
        gbd.actualizardatosautor(t,n);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CONSULTADOS;
    private javax.swing.JTable CONSULTATRES;
    private javax.swing.JRadioButton boton1;
    private javax.swing.JButton btnActualizarfechad;
    private javax.swing.JButton btnActualizarfechad1;
    private javax.swing.JButton btnActualizarfechap;
    private javax.swing.JButton btnActualizarfechap1;
    private javax.swing.JButton btnActualizaridprestamo;
    private javax.swing.JButton btnActualizaridprestamo1;
    private javax.swing.JButton btnActualizarrutcli;
    private javax.swing.JButton btnActualizarrutcli1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarprestamo;
    private javax.swing.JButton btnELIMINARLIBRO;
    private javax.swing.JButton btnELIMINARPRESTAMO;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JRadioButton btnIDPRESTAMO;
    private javax.swing.JButton btnIntegrantes;
    private javax.swing.JRadioButton btnRUT;
    private javax.swing.JCheckBox btnSTOCK;
    private javax.swing.JButton btnSTOCKK;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnmostrar1;
    private javax.swing.JButton btnmostrar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tmostrar;
    private javax.swing.JTable tmostrar1;
    private javax.swing.JTable tmostrar2;
    private javax.swing.JTextField txtADLA;
    private javax.swing.JTextField txtADLA1;
    private javax.swing.JTextField txtADLA2;
    private javax.swing.JTextField txtADLN;
    private javax.swing.JTextField txtADLN1;
    private javax.swing.JTextField txtADLN2;
    private javax.swing.JTextField txtADLT;
    private javax.swing.JTextField txtADLT1;
    private javax.swing.JTextField txtADLT2;
    private javax.swing.JTextField txtADLT3;
    private javax.swing.JTextField txtADLT4;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDire;
    private javax.swing.JTextField txtELIMINARLIBRO;
    private javax.swing.JTextField txtELIMINARPRESTAMO;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JButton txtLibroagregar;
    private javax.swing.JTextField txtLibroautor;
    private javax.swing.JTextField txtLibronombre;
    private javax.swing.JTextField txtLibrotipo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPdevolucion;
    private javax.swing.JTextField txtPlibro;
    private javax.swing.JTextField txtPprestamo;
    private javax.swing.JTextField txtPrestamo;
    private javax.swing.JTextField txtPrut;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStockk;
    private javax.swing.JTextField txtidlibro;
    private javax.swing.JTextField txtidlibro1;
    private javax.swing.JTextField txtidlibro2;
    // End of variables declaration//GEN-END:variables
}
